display_name: Lantern
msix_version: 2.1.5.0
publisher_display_name: lantern
identity_name: org.getlantern.lantern
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient, internetClientServer, privateNetworkClientServer
languages: en-us, ru-ru, zh-cn, zh-tw