const defaultTapTimeout = Duration(seconds: 1);
const defaultWaitTimeout = Duration(seconds: 5);
const longWaitTimeout = Duration(seconds: 20);
const veryLongWaitTimeout = Duration(seconds: 40);
const textThisNumber = '220 818 331 908';
const dummyText = 'I want to eat some pizza 🍕 😊';
const dummyReply = 'Actually no, I think I am in the mood for sushi today!';
const contactNewName = 'Layla B';
const recoveryKey = '8k171bwe866wd4apxyxtu9e2r92tmcdbgar35ymjx6b4ymhymugy';
