
// Objective-C API for talking to the following Go packages
//
//	github.com/getlantern/flashlight/v7/ios
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ios_FRAMEWORK_H__
#define __Ios_FRAMEWORK_H__

#include "Ios.objc.h"
#include "Universe.objc.h"

#endif
