disabled_rules:
- trailing_whitespace
- identifier_name
- line_length
opt_in_rules:
- empty_count
- empty_string
- vertical_whitespace_closing_braces
- redundant_optional_initialization
- explicit_self
- vertical_parameter_alignment
- weak_delegate
included: # paths to include during linting. `--path` is ignored if present.
  - Source
  - Runner
excluded:
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 150
    error: 200
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"
