source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'
use_frameworks! :linkage => :static
$casVersion = '~> 3.5.1'
inhibit_all_warnings!
# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
   use_frameworks! :linkage => :static
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

# target 'LanternTests' do
#   use_frameworks!
#   use_modular_headers!
#
#   flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
#    pod 'SQLite.swift', '~> 0.12.2'
#    pod 'Toast-Swift', '~> 5.0.1'
# end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    flutter_additional_ios_build_settings(target)
#  end
#end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
              '$(inherited)',

              ## dart: PermissionGroup.calendar
              #'PERMISSION_EVENTS=0',

              ## dart: PermissionGroup.reminders
              #'PERMISSION_REMINDERS=0',

              ## dart: PermissionGroup.contacts
              # 'PERMISSION_CONTACTS=0',

              ## dart: PermissionGroup.camera
              # 'PERMISSION_CAMERA=0',

              ## dart: PermissionGroup.microphone
              'PERMISSION_MICROPHONE=0',

              ## dart: PermissionGroup.speech
              'PERMISSION_SPEECH_RECOGNIZER=0',

              ## dart: PermissionGroup.photos
              # 'PERMISSION_PHOTOS=0',

              ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
              # 'PERMISSION_LOCATION=0',

              ## dart: PermissionGroup.notification
              'PERMISSION_NOTIFICATIONS=0',

              ## dart: PermissionGroup.mediaLibrary
              'PERMISSION_MEDIA_LIBRARY=0',

              ## dart: PermissionGroup.sensors
              # 'PERMISSION_SENSORS=0'
            ]
    end
  end
end
