enum TAB_ENUM { MESSAGES, VPN, ACCOUNT }

enum FREE_ACCOUNT_ITEM {
  AUTHORIZE_DEVICE_FOR_PRO,
  INVITE_FRIENDS,
  DESKTOP_VERSION,
  FREE_YINBI_CRYPTO,
  SETTINGS,
}

enum PRO_ACCOUNT_ITEM {
  PRO_ACCOUNT_MANAGEMENT,
  ADD_DEVICE,
  INVITE_FRIENDS,
  DESKTOP_VERSION,
  FREE_YINBI_CRYPTO,
  SETTINGS,
}

enum SETTINGS_ENUM {
  AUTO_CONNECT,
  PROXY,
  LANGUAGE,
  REPORT,
}
