enum TAB_ENUM { VPN, EXCHANGE, ACCOUNT }

enum FREE_ACCOUNT_ITEM {
  UPGRADE_TO_LANTERN_PRO,
  AUTHORIZE_DEVICE_FOR_PRO,
  INVITE_FRIENDS,
  DESKTOP_VERSION,
  FREE_YINBI_CRYPTO,
  SETTINGS,
}

enum PRO_ACCOUNT_ITEM {
  PRO_ACCOUNT_MANAGEMENT,
  ADD_DEVICE,
  INVITE_FRIENDS,
  DESKTOP_VERSION,
  YINBI_REDEMPTION,
  SETTINGS,
}