
// Objective-C API for talking to the following Go packages
//
//	github.com/getlantern/android-lantern/internalsdk
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Internalsdk_FRAMEWORK_H__
#define __Internalsdk_FRAMEWORK_H__

#include "Internalsdk.objc.h"
#include "Universe.objc.h"

#endif
