// Objective-C API for talking to github.com/getlantern/android-lantern/internalsdk Go package.
//   gobind -lang=objc github.com/getlantern/android-lantern/internalsdk
//
// File is generated by gobind. Do not edit.

#ifndef __Internalsdk_H__
#define __Internalsdk_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Minisql.objc.h"

@protocol InternalsdkModel;
@class InternalsdkModel;

@protocol InternalsdkModel <NSObject>
- (MinisqlValue* _Nullable)invokeMethod:(NSString* _Nullable)method arguments:(id<MinisqlValues> _Nullable)arguments error:(NSError* _Nullable* _Nullable)error;
@end

FOUNDATION_EXPORT id<InternalsdkModel> _Nullable InternalsdkNewModel(NSString* _Nullable schema, id<MinisqlDB> _Nullable mdb, NSError* _Nullable* _Nullable error);

@class InternalsdkModel;

@interface InternalsdkModel : NSObject <goSeqRefInterface, InternalsdkModel> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (MinisqlValue* _Nullable)invokeMethod:(NSString* _Nullable)method arguments:(id<MinisqlValues> _Nullable)arguments error:(NSError* _Nullable* _Nullable)error;
@end

#endif
