// Mocks generated by Mockito 5.4.4 from annotations
// in lantern/test/utils/test.mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ffi' as _i5;
import 'dart:typed_data' as _i8;

import 'package:lantern/core/utils/common.dart' as _i2;
import 'package:lantern/core/utils/common_desktop.dart' as _i3;
import 'package:lantern/core/utils/utils.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEventManager_0 extends _i1.SmartFake implements _i2.EventManager {
  _FakeEventManager_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueNotifier_1<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFfiListNotifier_2<T> extends _i1.SmartFake
    implements _i3.FfiListNotifier<T> {
  _FakeFfiListNotifier_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMethodChannel_3 extends _i1.SmartFake implements _i2.MethodChannel {
  _FakeMethodChannel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWidget_4 extends _i1.SmartFake implements _i2.Widget {
  _FakeWidget_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeFuture_5<T1> extends _i1.SmartFake implements _i4.Future<T1> {
  _FakeFuture_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeValueListenableBuilder_6<T1> extends _i1.SmartFake
    implements _i2.ValueListenableBuilder<T1> {
  _FakeValueListenableBuilder_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i2.DiagnosticLevel? minLevel = _i2.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [SessionModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionModel extends _i1.Mock implements _i2.SessionModel {
  @override
  _i2.EventManager get eventManager => (super.noSuchMethod(
        Invocation.getter(#eventManager),
        returnValue: _FakeEventManager_0(
          this,
          Invocation.getter(#eventManager),
        ),
        returnValueForMissingStub: _FakeEventManager_0(
          this,
          Invocation.getter(#eventManager),
        ),
      ) as _i2.EventManager);

  @override
  set eventManager(_i2.EventManager? _eventManager) => super.noSuchMethod(
        Invocation.setter(
          #eventManager,
          _eventManager,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<bool> get networkAvailable => (super.noSuchMethod(
        Invocation.getter(#networkAvailable),
        returnValue: _FakeValueNotifier_1<bool>(
          this,
          Invocation.getter(#networkAvailable),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<bool>(
          this,
          Invocation.getter(#networkAvailable),
        ),
      ) as _i2.ValueNotifier<bool>);

  @override
  set networkAvailable(_i2.ValueNotifier<bool>? _networkAvailable) =>
      super.noSuchMethod(
        Invocation.setter(
          #networkAvailable,
          _networkAvailable,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<bool?> get isTestPlayVersion => (super.noSuchMethod(
        Invocation.getter(#isTestPlayVersion),
        returnValue: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#isTestPlayVersion),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#isTestPlayVersion),
        ),
      ) as _i2.ValueNotifier<bool?>);

  @override
  set isTestPlayVersion(_i2.ValueNotifier<bool?>? _isTestPlayVersion) =>
      super.noSuchMethod(
        Invocation.setter(
          #isTestPlayVersion,
          _isTestPlayVersion,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<bool?> get isStoreVersion => (super.noSuchMethod(
        Invocation.getter(#isStoreVersion),
        returnValue: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#isStoreVersion),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#isStoreVersion),
        ),
      ) as _i2.ValueNotifier<bool?>);

  @override
  set isStoreVersion(_i2.ValueNotifier<bool?>? _isStoreVersion) =>
      super.noSuchMethod(
        Invocation.setter(
          #isStoreVersion,
          _isStoreVersion,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<bool?> get proxyAvailable => (super.noSuchMethod(
        Invocation.getter(#proxyAvailable),
        returnValue: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#proxyAvailable),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#proxyAvailable),
        ),
      ) as _i2.ValueNotifier<bool?>);

  @override
  set proxyAvailable(_i2.ValueNotifier<bool?>? _proxyAvailable) =>
      super.noSuchMethod(
        Invocation.setter(
          #proxyAvailable,
          _proxyAvailable,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<bool?> get proUserNotifier => (super.noSuchMethod(
        Invocation.getter(#proUserNotifier),
        returnValue: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#proUserNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#proUserNotifier),
        ),
      ) as _i2.ValueNotifier<bool?>);

  @override
  set proUserNotifier(_i2.ValueNotifier<bool?>? _proUserNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #proUserNotifier,
          _proUserNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<_i3.ConfigOptions?> get configNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#configNotifier),
        returnValue: _FakeValueNotifier_1<_i3.ConfigOptions?>(
          this,
          Invocation.getter(#configNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<_i3.ConfigOptions?>(
          this,
          Invocation.getter(#configNotifier),
        ),
      ) as _i2.ValueNotifier<_i3.ConfigOptions?>);

  @override
  set configNotifier(_i2.ValueNotifier<_i3.ConfigOptions?>? _configNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #configNotifier,
          _configNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<String?> get country => (super.noSuchMethod(
        Invocation.getter(#country),
        returnValue: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#country),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#country),
        ),
      ) as _i2.ValueNotifier<String?>);

  @override
  set country(_i2.ValueNotifier<String?>? _country) => super.noSuchMethod(
        Invocation.setter(
          #country,
          _country,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<String?> get referralNotifier => (super.noSuchMethod(
        Invocation.getter(#referralNotifier),
        returnValue: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#referralNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#referralNotifier),
        ),
      ) as _i2.ValueNotifier<String?>);

  @override
  set referralNotifier(_i2.ValueNotifier<String?>? _referralNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #referralNotifier,
          _referralNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<String?> get deviceIdNotifier => (super.noSuchMethod(
        Invocation.getter(#deviceIdNotifier),
        returnValue: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#deviceIdNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#deviceIdNotifier),
        ),
      ) as _i2.ValueNotifier<String?>);

  @override
  set deviceIdNotifier(_i2.ValueNotifier<String?>? _deviceIdNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #deviceIdNotifier,
          _deviceIdNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<String?> get langNotifier => (super.noSuchMethod(
        Invocation.getter(#langNotifier),
        returnValue: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#langNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#langNotifier),
        ),
      ) as _i2.ValueNotifier<String?>);

  @override
  set langNotifier(_i2.ValueNotifier<String?>? _langNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #langNotifier,
          _langNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<bool> get proxyAllNotifier => (super.noSuchMethod(
        Invocation.getter(#proxyAllNotifier),
        returnValue: _FakeValueNotifier_1<bool>(
          this,
          Invocation.getter(#proxyAllNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<bool>(
          this,
          Invocation.getter(#proxyAllNotifier),
        ),
      ) as _i2.ValueNotifier<bool>);

  @override
  set proxyAllNotifier(_i2.ValueNotifier<bool>? _proxyAllNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #proxyAllNotifier,
          _proxyAllNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<_i2.ServerInfo?> get serverInfoNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#serverInfoNotifier),
        returnValue: _FakeValueNotifier_1<_i2.ServerInfo?>(
          this,
          Invocation.getter(#serverInfoNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<_i2.ServerInfo?>(
          this,
          Invocation.getter(#serverInfoNotifier),
        ),
      ) as _i2.ValueNotifier<_i2.ServerInfo?>);

  @override
  set serverInfoNotifier(
          _i2.ValueNotifier<_i2.ServerInfo?>? _serverInfoNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #serverInfoNotifier,
          _serverInfoNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<String?> get userEmail => (super.noSuchMethod(
        Invocation.getter(#userEmail),
        returnValue: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#userEmail),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#userEmail),
        ),
      ) as _i2.ValueNotifier<String?>);

  @override
  set userEmail(_i2.ValueNotifier<String?>? _userEmail) => super.noSuchMethod(
        Invocation.setter(
          #userEmail,
          _userEmail,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<String?> get linkingCodeNotifier => (super.noSuchMethod(
        Invocation.getter(#linkingCodeNotifier),
        returnValue: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#linkingCodeNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<String?>(
          this,
          Invocation.getter(#linkingCodeNotifier),
        ),
      ) as _i2.ValueNotifier<String?>);

  @override
  set linkingCodeNotifier(_i2.ValueNotifier<String?>? _linkingCodeNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #linkingCodeNotifier,
          _linkingCodeNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<_i2.Devices?> get devicesNotifier => (super.noSuchMethod(
        Invocation.getter(#devicesNotifier),
        returnValue: _FakeValueNotifier_1<_i2.Devices?>(
          this,
          Invocation.getter(#devicesNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<_i2.Devices?>(
          this,
          Invocation.getter(#devicesNotifier),
        ),
      ) as _i2.ValueNotifier<_i2.Devices?>);

  @override
  set devicesNotifier(_i2.ValueNotifier<_i2.Devices?>? _devicesNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #devicesNotifier,
          _devicesNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<bool?> get hasUserSignedInNotifier => (super.noSuchMethod(
        Invocation.getter(#hasUserSignedInNotifier),
        returnValue: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#hasUserSignedInNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#hasUserSignedInNotifier),
        ),
      ) as _i2.ValueNotifier<bool?>);

  @override
  set hasUserSignedInNotifier(
          _i2.ValueNotifier<bool?>? _hasUserSignedInNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #hasUserSignedInNotifier,
          _hasUserSignedInNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<bool?> get isAuthEnabled => (super.noSuchMethod(
        Invocation.getter(#isAuthEnabled),
        returnValue: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#isAuthEnabled),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<bool?>(
          this,
          Invocation.getter(#isAuthEnabled),
        ),
      ) as _i2.ValueNotifier<bool?>);

  @override
  set isAuthEnabled(_i2.ValueNotifier<bool?>? _isAuthEnabled) =>
      super.noSuchMethod(
        Invocation.setter(
          #isAuthEnabled,
          _isAuthEnabled,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.FfiListNotifier<_i2.Plan> get plansNotifier => (super.noSuchMethod(
        Invocation.getter(#plansNotifier),
        returnValue: _FakeFfiListNotifier_2<_i2.Plan>(
          this,
          Invocation.getter(#plansNotifier),
        ),
        returnValueForMissingStub: _FakeFfiListNotifier_2<_i2.Plan>(
          this,
          Invocation.getter(#plansNotifier),
        ),
      ) as _i3.FfiListNotifier<_i2.Plan>);

  @override
  set plansNotifier(_i3.FfiListNotifier<_i2.Plan>? _plansNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #plansNotifier,
          _plansNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.FfiListNotifier<_i2.PaymentMethod> get paymentMethodsNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#paymentMethodsNotifier),
        returnValue: _FakeFfiListNotifier_2<_i2.PaymentMethod>(
          this,
          Invocation.getter(#paymentMethodsNotifier),
        ),
        returnValueForMissingStub: _FakeFfiListNotifier_2<_i2.PaymentMethod>(
          this,
          Invocation.getter(#paymentMethodsNotifier),
        ),
      ) as _i3.FfiListNotifier<_i2.PaymentMethod>);

  @override
  set paymentMethodsNotifier(
          _i3.FfiListNotifier<_i2.PaymentMethod>? _paymentMethodsNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #paymentMethodsNotifier,
          _paymentMethodsNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<_i2.Bandwidth?> get bandwidthNotifier =>
      (super.noSuchMethod(
        Invocation.getter(#bandwidthNotifier),
        returnValue: _FakeValueNotifier_1<_i2.Bandwidth?>(
          this,
          Invocation.getter(#bandwidthNotifier),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<_i2.Bandwidth?>(
          this,
          Invocation.getter(#bandwidthNotifier),
        ),
      ) as _i2.ValueNotifier<_i2.Bandwidth?>);

  @override
  set bandwidthNotifier(
          _i2.ValueNotifier<_i2.Bandwidth?>? _bandwidthNotifier) =>
      super.noSuchMethod(
        Invocation.setter(
          #bandwidthNotifier,
          _bandwidthNotifier,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.MethodChannel get methodChannel => (super.noSuchMethod(
        Invocation.getter(#methodChannel),
        returnValue: _FakeMethodChannel_3(
          this,
          Invocation.getter(#methodChannel),
        ),
        returnValueForMissingStub: _FakeMethodChannel_3(
          this,
          Invocation.getter(#methodChannel),
        ),
      ) as _i2.MethodChannel);

  @override
  set methodChannel(_i2.MethodChannel? _methodChannel) => super.noSuchMethod(
        Invocation.setter(
          #methodChannel,
          _methodChannel,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set event(_i2.Event? _event) => super.noSuchMethod(
        Invocation.setter(
          #event,
          _event,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.ValueNotifier<T?> pathValueNotifier<T>(
    String? path,
    T? defaultValue,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #pathValueNotifier,
          [
            path,
            defaultValue,
          ],
        ),
        returnValue: _FakeValueNotifier_1<T?>(
          this,
          Invocation.method(
            #pathValueNotifier,
            [
              path,
              defaultValue,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<T?>(
          this,
          Invocation.method(
            #pathValueNotifier,
            [
              path,
              defaultValue,
            ],
          ),
        ),
      ) as _i2.ValueNotifier<T?>);

  @override
  _i4.Future<void> updateUserDetails() => (super.noSuchMethod(
        Invocation.method(
          #updateUserDetails,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.Widget configValueBuilder<T>(
    String? path,
    _i2.ValueWidgetBuilder<T>? builder,
    T Function(_i3.ConfigOptions?)? onConfigUpdate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #configValueBuilder,
          [
            path,
            builder,
            onConfigUpdate,
          ],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #configValueBuilder,
            [
              path,
              builder,
              onConfigUpdate,
            ],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #configValueBuilder,
            [
              path,
              builder,
              onConfigUpdate,
            ],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget proUser(_i2.ValueWidgetBuilder<bool>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #proUser,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #proUser,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #proUser,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget bandwidth(_i2.ValueWidgetBuilder<_i2.Bandwidth>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #bandwidth,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #bandwidth,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #bandwidth,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget developmentMode(_i2.ValueWidgetBuilder<bool>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #developmentMode,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #developmentMode,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #developmentMode,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget paymentTestMode(_i2.ValueWidgetBuilder<bool>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #paymentTestMode,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #paymentTestMode,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #paymentTestMode,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<void> setPaymentTestMode(bool? on) => (super.noSuchMethod(
        Invocation.method(
          #setPaymentTestMode,
          [on],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> acceptTerms() => (super.noSuchMethod(
        Invocation.method(
          #acceptTerms,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.Widget acceptedTermsVersion(_i2.ValueWidgetBuilder<int>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #acceptedTermsVersion,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #acceptedTermsVersion,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #acceptedTermsVersion,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget forceCountry(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #forceCountry,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #forceCountry,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #forceCountry,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<void> setForceCountry(String? countryCode) => (super.noSuchMethod(
        Invocation.method(
          #setForceCountry,
          [countryCode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.Widget geoCountryCode(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #geoCountryCode,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #geoCountryCode,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #geoCountryCode,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget storeVersion(_i2.ValueWidgetBuilder<bool>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeVersion,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #storeVersion,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #storeVersion,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget testPlayVersion(_i2.ValueWidgetBuilder<bool>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #testPlayVersion,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #testPlayVersion,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #testPlayVersion,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<void> setTestPlayVersion(bool? on) => (super.noSuchMethod(
        Invocation.method(
          #setTestPlayVersion,
          [on],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.Widget language(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #language,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #language,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #language,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget emailAddress(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #emailAddress,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #emailAddress,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #emailAddress,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget expiryDate(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #expiryDate,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #expiryDate,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #expiryDate,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget referralCode(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #referralCode,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #referralCode,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #referralCode,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget deviceId(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #deviceId,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #deviceId,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #deviceId,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget devices(_i2.ValueWidgetBuilder<_i2.Devices>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #devices,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #devices,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #devices,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<void> testProviderRequest(
    String? email,
    String? paymentProvider,
    String? planId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #testProviderRequest,
          [
            email,
            paymentProvider,
            planId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i5.Pointer<_i3.Utf8> ffiIsUserLoggedIn() => (super.noSuchMethod(
        Invocation.method(
          #ffiIsUserLoggedIn,
          [],
        ),
        returnValue: _i6.dummyValue<_i5.Pointer<_i3.Utf8>>(
          this,
          Invocation.method(
            #ffiIsUserLoggedIn,
            [],
          ),
        ),
        returnValueForMissingStub: _i6.dummyValue<_i5.Pointer<_i3.Utf8>>(
          this,
          Invocation.method(
            #ffiIsUserLoggedIn,
            [],
          ),
        ),
      ) as _i5.Pointer<_i3.Utf8>);

  @override
  _i2.Widget isUserSignedIn(_i2.ValueWidgetBuilder<bool>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #isUserSignedIn,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #isUserSignedIn,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #isUserSignedIn,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<void> signUp(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signUpEmailResendCode(String? email) => (super.noSuchMethod(
        Invocation.method(
          #signUpEmailResendCode,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signupEmailConfirmation(
    String? email,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signupEmailConfirmation,
          [
            email,
            code,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> startRecoveryByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #startRecoveryByEmail,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> completeRecoveryByEmail(
    String? email,
    String? password,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeRecoveryByEmail,
          [
            email,
            password,
            code,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> validateRecoveryCode(
    String? email,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateRecoveryCode,
          [
            email,
            code,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> startChangeEmail(
    String? email,
    String? newEmail,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #startChangeEmail,
          [
            email,
            newEmail,
            password,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> completeChangeEmail(
    String? email,
    String? newEmail,
    String? password,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeChangeEmail,
          [
            email,
            newEmail,
            password,
            code,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAccount(String? password) => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [password],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> isUserFirstTimeVisit() => (super.noSuchMethod(
        Invocation.method(
          #isUserFirstTimeVisit,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> setFirstTimeVisit() => (super.noSuchMethod(
        Invocation.method(
          #setFirstTimeVisit,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setProxyAll<T>(bool? isOn) => (super.noSuchMethod(
        Invocation.method(
          #setProxyAll,
          [isOn],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> proxyAddr() => (super.noSuchMethod(
        Invocation.method(
          #proxyAddr,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #proxyAddr,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #proxyAddr,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> getCountryCode() => (super.noSuchMethod(
        Invocation.method(
          #getCountryCode,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getCountryCode,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getCountryCode,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> setLanguage(String? lang) => (super.noSuchMethod(
        Invocation.method(
          #setLanguage,
          [lang],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> userEmailRequest(String? email) => (super.noSuchMethod(
        Invocation.method(
          #userEmailRequest,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> authorizeViaEmail(String? emailAddress) =>
      (super.noSuchMethod(
        Invocation.method(
          #authorizeViaEmail,
          [emailAddress],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> validateDeviceRecoveryCode(
    String? code,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateDeviceRecoveryCode,
          [
            code,
            email,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> approveDevice(String? code) => (super.noSuchMethod(
        Invocation.method(
          #approveDevice,
          [code],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeDevice(String? deviceId) => (super.noSuchMethod(
        Invocation.method(
          #removeDevice,
          [deviceId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resendRecoveryCode() => (super.noSuchMethod(
        Invocation.method(
          #resendRecoveryCode,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void setSelectedTab(
    _i2.BuildContext? context,
    String? tab,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #setSelectedTab,
          [
            context,
            tab,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Widget shouldShowAds(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #shouldShowAds,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #shouldShowAds,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #shouldShowAds,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget replicaAddr(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #replicaAddr,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #replicaAddr,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #replicaAddr,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget countryCode(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #countryCode,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #countryCode,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #countryCode,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<String> getReplicaAddr() => (super.noSuchMethod(
        Invocation.method(
          #getReplicaAddr,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getReplicaAddr,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #getReplicaAddr,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i2.Widget chatEnabled(_i2.ValueWidgetBuilder<bool>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #chatEnabled,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #chatEnabled,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #chatEnabled,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget sdkVersion(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #sdkVersion,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #sdkVersion,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #sdkVersion,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<bool> getChatEnabled() => (super.noSuchMethod(
        Invocation.method(
          #getChatEnabled,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<String?> checkForUpdates() => (super.noSuchMethod(
        Invocation.method(
          #checkForUpdates,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> restoreAccount(
    String? email,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreAccount,
          [
            email,
            code,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePaymentPlans() => (super.noSuchMethod(
        Invocation.method(
          #updatePaymentPlans,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> hasUpdatePlansOrBuy() => (super.noSuchMethod(
        Invocation.method(
          #hasUpdatePlansOrBuy,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i2.Widget plans(
          {required _i2
              .ValueWidgetBuilder<Iterable<_i2.PathAndValue<_i2.Plan>>>?
              builder}) =>
      (super.noSuchMethod(
        Invocation.method(
          #plans,
          [],
          {#builder: builder},
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #plans,
            [],
            {#builder: builder},
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #plans,
            [],
            {#builder: builder},
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget paymentMethods(
          {required _i2.ValueWidgetBuilder<
                  Iterable<_i2.PathAndValue<_i2.PaymentMethod>>>?
              builder}) =>
      (super.noSuchMethod(
        Invocation.method(
          #paymentMethods,
          [],
          {#builder: builder},
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #paymentMethods,
            [],
            {#builder: builder},
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #paymentMethods,
            [],
            {#builder: builder},
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<void> applyRefCode(String? refCode) => (super.noSuchMethod(
        Invocation.method(
          #applyRefCode,
          [refCode],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reportIssue(
    String? email,
    String? issue,
    String? description,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportIssue,
          [
            email,
            issue,
            description,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.Widget getUserId(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserId,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #getUserId,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #getUserId,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget userStatus(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #userStatus,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #userStatus,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #userStatus,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget serverInfo(_i2.ValueWidgetBuilder<_i2.ServerInfo?>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #serverInfo,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #serverInfo,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #serverInfo,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<void> trackUserAction(
    String? name,
    String? url, [
    String? title = r'',
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #trackUserAction,
          [
            name,
            url,
            title,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> requestLinkCode() => (super.noSuchMethod(
        Invocation.method(
          #requestLinkCode,
          [],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #requestLinkCode,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #requestLinkCode,
            [],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> redeemLinkCode() => (super.noSuchMethod(
        Invocation.method(
          #redeemLinkCode,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.Widget deviceLinkingCode(_i2.ValueWidgetBuilder<String>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #deviceLinkingCode,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #deviceLinkingCode,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #deviceLinkingCode,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<void> redeemResellerCode(
    String? email,
    String? currency,
    String? deviceName,
    String? resellerCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #redeemResellerCode,
          [
            email,
            currency,
            deviceName,
            resellerCode,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> submitBitcoinPayment(
    String? planID,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitBitcoinPayment,
          [
            planID,
            email,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #submitBitcoinPayment,
            [
              planID,
              email,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #submitBitcoinPayment,
            [
              planID,
              email,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> generatePaymentRedirectUrl({
    required String? planID,
    required String? email,
    required _i7.Providers? paymentProvider,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generatePaymentRedirectUrl,
          [],
          {
            #planID: planID,
            #email: email,
            #paymentProvider: paymentProvider,
          },
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #generatePaymentRedirectUrl,
            [],
            {
              #planID: planID,
              #email: email,
              #paymentProvider: paymentProvider,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #generatePaymentRedirectUrl,
            [],
            {
              #planID: planID,
              #email: email,
              #paymentProvider: paymentProvider,
            },
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<bool> isGooglePlayServiceAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isGooglePlayServiceAvailable,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> submitPlayPayment(
    String? planID,
    String? email,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitPlayPayment,
          [
            planID,
            email,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> paymentRedirectForDesktop(
    _i2.BuildContext? context,
    String? planID,
    String? email,
    _i7.Providers? provider,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #paymentRedirectForDesktop,
          [
            context,
            planID,
            email,
            provider,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #paymentRedirectForDesktop,
            [
              context,
              planID,
              email,
              provider,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #paymentRedirectForDesktop,
            [
              context,
              planID,
              email,
              provider,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> submitApplePlay(
    String? email,
    String? planID,
    String? purchaseToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitApplePlay,
          [
            email,
            planID,
            purchaseToken,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> submitStripePayment(
    String? planID,
    String? email,
    String? cardNumber,
    String? expDate,
    String? cvc,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitStripePayment,
          [
            planID,
            email,
            cardNumber,
            expDate,
            cvc,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> submitFreekassa(
    String? email,
    String? planID,
    String? currencyPrice,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #submitFreekassa,
          [
            email,
            planID,
            currencyPrice,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> checkEmailExists(String? email) => (super.noSuchMethod(
        Invocation.method(
          #checkEmailExists,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> refreshAppsList() => (super.noSuchMethod(
        Invocation.method(
          #refreshAppsList,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.Widget splitTunneling(_i2.ValueWidgetBuilder<bool>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #splitTunneling,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #splitTunneling,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #splitTunneling,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i2.Widget proxyAll(_i2.ValueWidgetBuilder<bool>? builder) =>
      (super.noSuchMethod(
        Invocation.method(
          #proxyAll,
          [builder],
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #proxyAll,
            [builder],
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #proxyAll,
            [builder],
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<void> setSplitTunneling<T>(bool? on) => (super.noSuchMethod(
        Invocation.method(
          #setSplitTunneling,
          [on],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i2.Widget appsData(
          {required _i2
              .ValueWidgetBuilder<Iterable<_i2.PathAndValue<_i2.AppData>>>?
              builder}) =>
      (super.noSuchMethod(
        Invocation.method(
          #appsData,
          [],
          {#builder: builder},
        ),
        returnValue: _FakeWidget_4(
          this,
          Invocation.method(
            #appsData,
            [],
            {#builder: builder},
          ),
        ),
        returnValueForMissingStub: _FakeWidget_4(
          this,
          Invocation.method(
            #appsData,
            [],
            {#builder: builder},
          ),
        ),
      ) as _i2.Widget);

  @override
  _i4.Future<void> allowAppAccess(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #allowAppAccess,
          [packageName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> denyAppAccess(String? packageName) => (super.noSuchMethod(
        Invocation.method(
          #denyAppAccess,
          [packageName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> enableScreenShot() => (super.noSuchMethod(
        Invocation.method(
          #enableScreenShot,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> disableScreenShot() => (super.noSuchMethod(
        Invocation.method(
          #disableScreenShot,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T> get<T>(String? path) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
        ),
        returnValue: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_5<T>(
              this,
              Invocation.method(
                #get,
                [path],
              ),
            ),
        returnValueForMissingStub: _i6.ifNotNull(
              _i6.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                ),
              ),
              (T v) => _i4.Future<T>.value(v),
            ) ??
            _FakeFuture_5<T>(
              this,
              Invocation.method(
                #get,
                [path],
              ),
            ),
      ) as _i4.Future<T>);

  @override
  _i4.Future<List<T>> list<T>(
    String? path, {
    int? start = 0,
    int? count = 34,
    String? fullTextSearch,
    bool? reverseSort = false,
    T Function(_i8.Uint8List)? deserialize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #list,
          [path],
          {
            #start: start,
            #count: count,
            #fullTextSearch: fullTextSearch,
            #reverseSort: reverseSort,
            #deserialize: deserialize,
          },
        ),
        returnValue: _i4.Future<List<T>>.value(<T>[]),
        returnValueForMissingStub: _i4.Future<List<T>>.value(<T>[]),
      ) as _i4.Future<List<T>>);

  @override
  _i2.ValueListenableBuilder<T?> subscribedSingleValueBuilder<T>(
    String? path, {
    T? defaultValue,
    required _i2.ValueWidgetBuilder<T>? builder,
    bool? details = false,
    T Function(_i8.Uint8List)? deserialize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #subscribedSingleValueBuilder,
          [path],
          {
            #defaultValue: defaultValue,
            #builder: builder,
            #details: details,
            #deserialize: deserialize,
          },
        ),
        returnValue: _FakeValueListenableBuilder_6<T?>(
          this,
          Invocation.method(
            #subscribedSingleValueBuilder,
            [path],
            {
              #defaultValue: defaultValue,
              #builder: builder,
              #details: details,
              #deserialize: deserialize,
            },
          ),
        ),
        returnValueForMissingStub: _FakeValueListenableBuilder_6<T?>(
          this,
          Invocation.method(
            #subscribedSingleValueBuilder,
            [path],
            {
              #defaultValue: defaultValue,
              #builder: builder,
              #details: details,
              #deserialize: deserialize,
            },
          ),
        ),
      ) as _i2.ValueListenableBuilder<T?>);

  @override
  _i2.ValueNotifier<T?> singleValueNotifier<T>(
    String? path,
    T? defaultValue, {
    bool? details = false,
    T Function(_i8.Uint8List)? deserialize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #singleValueNotifier,
          [
            path,
            defaultValue,
          ],
          {
            #details: details,
            #deserialize: deserialize,
          },
        ),
        returnValue: _FakeValueNotifier_1<T?>(
          this,
          Invocation.method(
            #singleValueNotifier,
            [
              path,
              defaultValue,
            ],
            {
              #details: details,
              #deserialize: deserialize,
            },
          ),
        ),
        returnValueForMissingStub: _FakeValueNotifier_1<T?>(
          this,
          Invocation.method(
            #singleValueNotifier,
            [
              path,
              defaultValue,
            ],
            {
              #details: details,
              #deserialize: deserialize,
            },
          ),
        ),
      ) as _i2.ValueNotifier<T?>);

  @override
  _i2.ValueListenableBuilder<_i2.ChangeTrackingList<T>>
      subscribedListBuilder<T>(
    String? path, {
    required _i2.ValueWidgetBuilder<Iterable<_i2.PathAndValue<T>>>? builder,
    bool? details = false,
    int Function(
      String,
      String,
    )? compare,
    T Function(_i8.Uint8List)? deserialize,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #subscribedListBuilder,
              [path],
              {
                #builder: builder,
                #details: details,
                #compare: compare,
                #deserialize: deserialize,
              },
            ),
            returnValue:
                _FakeValueListenableBuilder_6<_i2.ChangeTrackingList<T>>(
              this,
              Invocation.method(
                #subscribedListBuilder,
                [path],
                {
                  #builder: builder,
                  #details: details,
                  #compare: compare,
                  #deserialize: deserialize,
                },
              ),
            ),
            returnValueForMissingStub:
                _FakeValueListenableBuilder_6<_i2.ChangeTrackingList<T>>(
              this,
              Invocation.method(
                #subscribedListBuilder,
                [path],
                {
                  #builder: builder,
                  #details: details,
                  #compare: compare,
                  #deserialize: deserialize,
                },
              ),
            ),
          ) as _i2.ValueListenableBuilder<_i2.ChangeTrackingList<T>>);

  @override
  _i2.ValueNotifier<_i2.ChangeTrackingList<T>> listNotifier<T>(
    String? path, {
    bool? details = false,
    int Function(
      String,
      String,
    )? compare,
    T Function(_i8.Uint8List)? deserialize,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listNotifier,
          [path],
          {
            #details: details,
            #compare: compare,
            #deserialize: deserialize,
          },
        ),
        returnValue: _FakeValueNotifier_1<_i2.ChangeTrackingList<T>>(
          this,
          Invocation.method(
            #listNotifier,
            [path],
            {
              #details: details,
              #compare: compare,
              #deserialize: deserialize,
            },
          ),
        ),
        returnValueForMissingStub:
            _FakeValueNotifier_1<_i2.ChangeTrackingList<T>>(
          this,
          Invocation.method(
            #listNotifier,
            [path],
            {
              #details: details,
              #compare: compare,
              #deserialize: deserialize,
            },
          ),
        ),
      ) as _i2.ValueNotifier<_i2.ChangeTrackingList<T>>);

  @override
  _i2.ValueListenableBuilder<T> listChildBuilder<T>(
    _i2.BuildContext? context,
    String? path, {
    required T? defaultValue,
    required _i2.ValueWidgetBuilder<T>? builder,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listChildBuilder,
          [
            context,
            path,
          ],
          {
            #defaultValue: defaultValue,
            #builder: builder,
          },
        ),
        returnValue: _FakeValueListenableBuilder_6<T>(
          this,
          Invocation.method(
            #listChildBuilder,
            [
              context,
              path,
            ],
            {
              #defaultValue: defaultValue,
              #builder: builder,
            },
          ),
        ),
        returnValueForMissingStub: _FakeValueListenableBuilder_6<T>(
          this,
          Invocation.method(
            #listChildBuilder,
            [
              context,
              path,
            ],
            {
              #defaultValue: defaultValue,
              #builder: builder,
            },
          ),
        ),
      ) as _i2.ValueListenableBuilder<T>);
}
