## Uncomment the next line to define a global platform for your project
## platform :ios, '9.0'
#
target 'DatabaseFramework' do
  use_frameworks!
  pod 'SQLite.swift', '~> 0.12.0'

  target 'DatabaseFrameworkTests' do
    inherit! :search_paths
  end
end
