# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
# TODO: Update this to add Lantern to Windows app store
#app_id: 5B599538-42B1-4826-A479-AF079F21A65D
display_name: Lantern
create_desktop_icon: true