name: Build Linux
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      prefix:
        type: string
        required: true
      dist-suffix: # "arm64" or "amd64"
        type: string
        required: true

jobs:
  build-linux:
    permissions:
      contents: "read"
      id-token: "write"
    env:
      version: ${{ inputs.version }}
      prefix: ${{ inputs.prefix }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Granting private modules access
        run: git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
      - name: Repo access
        run: |
          mkdir /tmp/cache
          echo "machine github.com login ${{ secrets.GH_TOKEN }} password x-oauth-basic" > /tmp/cache/.netrc
          chmod 600 /tmp/cache/.netrc

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y file build-essential pkg-config
          sudo apt-get install -y libwebkit2gtk-4.1-dev
          sudo apt-get install -y libunwind-dev libstdc++-12-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-d cmake
          sudo apt-get install -y libgtk-3-0 libblkid1 liblzma5
          sudo apt-get install -y libpcap-dev libgtk-3-dev libayatana-appindicator3-dev ruby ruby-dev && sudo gem install bundler -v 2.2.26

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Build
        env:
          SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
          VERSION: ${{ inputs.version }}
        run: |
          make linux-amd64

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install s3cmd
        run: pip install s3cmd

      - name: Set s3cmd permissions
        run: |
          echo "[default]" > "$HOME/.s3cfg"
          echo "access_key = ${{ secrets.AWS_ACCESS_KEY }}" >> "$HOME/.s3cfg"
          echo "secret_key = ${{ secrets.AWS_SECRET_KEY }}" >> "$HOME/.s3cfg"

        # Install Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - run: flutter --version

      - run: make ffigen

      - name: Setup protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Activate Flutter plugins
        run: |
          dart pub global activate protoc_plugin
          dart pub global activate flutter_distributor

      - uses: seanmiddleditch/gha-setup-ninja@master

      - run: touch app.env

      - name: Build Flutter app
        run: flutter build linux

      - name: Build installer
        run: |
          cp liblantern.so "build/linux/${{inputs.dist-suffix}}/release/bundle"
          make package-linux
          mv dist/1.0.0+1/lantern-1.0.0+1-linux.deb lantern_${{inputs.version}}_x64.deb
          mv dist/1.0.0+1/lantern-1.0.0+1-linux.rpm lantern_${{inputs.version}}_x64.rpm

      - uses: actions/upload-artifact@v4
        with:
          name: linux-deb-build
          path: |
            lantern_${{inputs.version}}_x64.deb

      - uses: actions/upload-artifact@v4
        with:
          name: linux-rpm-build
          path: |
            lantern_${{inputs.version}}_x64.rpm

      - name: Push binaries to s3

        env:
          VERSION: "${{ inputs.version }}"
          dist_versionless: "${{inputs.prefix}}-64-bit.deb"
          dist_deb: "${{inputs.prefix}}-${{inputs.version}}-64-bit.deb"
          dist_deb_source: "lantern_${{inputs.version}}_x64.deb"
          dist_rpm: "${{inputs.prefix}}-${{inputs.version}}-64-bit.rpm"
          dist_rpm_source: "lantern_${{inputs.version}}_x64.rpm"
        run: |
          mv ${{ env.dist_deb_source }} ${{ env.dist_deb }}
          mv ${{ env.dist_rpm_source }} ${{ env.dist_rpm }}
          shasum -a 256 ${{ env.dist_deb }} | cut -d " " -f 1 > ${{ env.dist_deb }}.sha256
          shasum -a 256 ${{ env.dist_rpm }} | cut -d " " -f 1 > ${{ env.dist_rpm }}.sha256
          s3cmd put --acl-public ${{ env.dist_deb }} ${{ env.dist_deb }}.sha256 ${{ env.dist_rpm }} ${{ env.dist_rpm }}.sha256 "s3://lantern"
