name: Test Suite

on:
  push:
    branches:
      - main
      - jigar/setup-test-suite
#  pull_request:
#    branches:
#      - main

env:
  GOPRIVATE: github.com/getlantern


jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Pull LFS objects
        run: git lfs pull

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Granting private modules access
        run: git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup protoc
        uses: arduino/setup-protoc@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install latest protoc-gen-go
        run: go install github.com/golang/protobuf/protoc-gen-go@latest

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        if: runner.os == 'macOS'
        with:
          xcode-version: latest-stable

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"


      - name: Install CLI
        run: |
          dart pub global activate protoc_plugin
          dart pub global activate patrol_cli

      - name: Install dependencies
        run: flutter pub get


      - name: Install Linux dependencies
        if: runner.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y file build-essential pkg-config
          sudo apt-get install -y libwebkit2gtk-4.1-dev
          sudo apt-get install -y libunwind-dev libstdc++-12-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-d cmake
          sudo apt-get install -y libgtk-3-0 libblkid1 liblzma5
          sudo apt-get install -y libpcap-dev libgtk-3-dev libayatana-appindicator3-dev ruby ruby-dev && sudo gem install bundler -v 2.2.26

      - name: Install the ninja build tool
        if: runner.os == 'linux'
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Generate app.env
        env:
          ANDROID_INTERSTITIAL_AD_ID: ${{ secrets.INTERSTITIAL_AD_UNIT_ID }}
          IOS_INTERSTITIAL_AD_ID: ${{ secrets.INTERSTITIAL_AD_UNIT_ID_IOS }}
          TAPSELL_VIDEO_INTERSTITIAL_ZONE_ID: ${{ secrets.TAPSELL_VIDEO_INTERSTITIAL_ZONE_ID }}
          TAPSELL_INTERSTITIAL_ZONE_ID: ${{ secrets.TAPSELL_INTERSTITIAL_ZONE_ID }}
        run: |
          touch app.env
          echo "Android_interstitialAd=$ANDROID_INTERSTITIAL_AD_ID" > app.env
          echo "IOS_interstitialAd=$IOS_INTERSTITIAL_AD_ID" >> app.env
          echo "VideoInterstitialZoneId=$TAPSELL_VIDEO_INTERSTITIAL_ZONE_ID" >> app.env
          echo "InterstitialZoneId=$TAPSELL_INTERSTITIAL_ZONE_ID" >> app.env

      - name: Build Libraries
        run: |
          make android ANDROID_ARCH=all
          make linux
          make ffigen
          flutter config --enable-linux-desktop

      - name: Running workflow test for macos
        run: make desktopWorkflowTest
        if: runner.os == 'macOS'
        timeout-minutes: 60

      - name: Running workflow test for linux
        uses: username/xvfb-action@v1.1.2
        if: runner.os == 'linux'
        timeout-minutes: 60
        with:
          run: make linuxDesktopTest


      - name: Running widget tests
        run: make widget-tests


      - name: Running workflow test for android on Firebase test labs
        run: make ci-android-test
